#!/usr/bin/env bash
set -euo pipefail

# AS-M4 12k staged launcher. Dry-run is intentionally supported so each
# integration phase can be smoke-tested without starting a long training job.

cd "$(dirname "$0")/.."

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
  STAGE="${2:-12k-smoke}"
else
  STAGE="${1:-12k-smoke}"
fi

LOG_DIR="${LOG_DIR:-train_logs}"
mkdir -p "$LOG_DIR"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,2,3,4}"
export NUM_GPUS="${NUM_GPUS:-4}"
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"
export NCCL_P2P_DISABLE=1
export NCCL_SHM_DISABLE=1
export NCCL_IB_DISABLE=1
export NCCL_SOCKET_IFNAME="${NCCL_SOCKET_IFNAME:-lo}"
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH:-12288}"
export M4_CHUNKED_LM_LOSS="${M4_CHUNKED_LM_LOSS:-1}"
export M4_CHUNKED_LM_LOSS_TOKENS="${M4_CHUNKED_LM_LOSS_TOKENS:-512}"
export M4_CHUNKED_LM_LOSS_CHECKPOINT="${M4_CHUNKED_LM_LOSS_CHECKPOINT:-0}"
export M4_FREEZE_LM_HEAD="${M4_FREEZE_LM_HEAD:-0}"
export DEEPSPEED_CONFIG="${DEEPSPEED_CONFIG:-scripts/zero3_lowmem.json}"
export AS_M4_ENABLE_SCENE_AUDIO="${AS_M4_ENABLE_SCENE_AUDIO:-1}"
export AS_M4_SCENE_AUDIO_ENCODER_TYPE="${AS_M4_SCENE_AUDIO_ENCODER_TYPE:-dummy}"
export AS_M4_SCENE_AUDIO_BEATS_CHECKPOINT="${AS_M4_SCENE_AUDIO_BEATS_CHECKPOINT:-intersuit/checkpoints/BEATs_iter3_plus_AS2M.pt}"
export AS_M4_SCENE_AUDIO_BEATS_CODE_ROOT="${AS_M4_SCENE_AUDIO_BEATS_CODE_ROOT:-third_party/OmniMMI/baselines/videollama2/model}"
export AS_M4_SCENE_AUDIO_BEATS_CHECKPOINT_SHA256="${AS_M4_SCENE_AUDIO_BEATS_CHECKPOINT_SHA256:-}"
export AS_M4_STREAMING_AV_LR="${AS_M4_STREAMING_AV_LR:-1e-4}"
export AS_M4_SCENE_AUDIO_PROJECTOR_LR="${AS_M4_SCENE_AUDIO_PROJECTOR_LR:-1e-4}"
export AS_M4_FUSION_INIT="${AS_M4_FUSION_INIT:-zero}"
export AS_M4_GATE_LOGIT_BIAS="${AS_M4_GATE_LOGIT_BIAS:--5.0}"
export AS_M4_FUSION_MODE="${AS_M4_FUSION_MODE:-aligned_gated}"
export AS_M4_SIMPLE_AUDIO_GATE="${AS_M4_SIMPLE_AUDIO_GATE:-1.0}"
export AS_M4_SCENE_AUDIO_WINDOW_MODE="${AS_M4_SCENE_AUDIO_WINDOW_MODE:-fixed}"
export AS_M4_DYNAMIC_WINDOW_SCALES_SEC="${AS_M4_DYNAMIC_WINDOW_SCALES_SEC:-1.0,2.0,4.0}"
export AS_M4_DYNAMIC_WINDOW_TOP_K="${AS_M4_DYNAMIC_WINDOW_TOP_K:-16}"
export AS_M4_DYNAMIC_WINDOW_NMS_IOU="${AS_M4_DYNAMIC_WINDOW_NMS_IOU:-0.6}"
export AS_M4_DYNAMIC_WINDOW_EMA_BETA="${AS_M4_DYNAMIC_WINDOW_EMA_BETA:-0.9}"
export AS_M4_DYNAMIC_WINDOW_START_SCALE="${AS_M4_DYNAMIC_WINDOW_START_SCALE:-1.0}"
export AS_M4_DYNAMIC_WINDOW_HOLD_SCALE="${AS_M4_DYNAMIC_WINDOW_HOLD_SCALE:-0.25}"
export AS_M4_DYNAMIC_WINDOW_MIN_SCORE="${AS_M4_DYNAMIC_WINDOW_MIN_SCORE:-0.05}"
export AS_M4_DYNAMIC_WINDOW_CAUSAL="${AS_M4_DYNAMIC_WINDOW_CAUSAL:-True}"
export AS_M4_FORCE_AUDIO_GATE="${AS_M4_FORCE_AUDIO_GATE:-}"
export AS_M4_ROLLBACK_MODE="${AS_M4_ROLLBACK_MODE:-none}"
export AS_M4_BASELINE_CKPT_12K="${AS_M4_BASELINE_CKPT_12K:-checkpoints/M4-LongVA-7B-Qwen2-train-12k-lowmem-nofreeze}"
export AS_M4_BASELINE_CKPT_32K="${AS_M4_BASELINE_CKPT_32K:-checkpoints/M4-LongVA-7B-Qwen2-repro-32k-lowmem-nofreeze-v1}"
export CKPT_PATH="${CKPT_PATH:-checkpoints/M4-LongVA-7B-Qwen2}"
export MM_TUNABLE_PARTS="${MM_TUNABLE_PARTS:-mm_vision_tower,mm_mlp_adapter,mm_language_model,streaming_av_module}"
export DATA_PATH="${DATA_PATH:-inputs/texts/m4-it-qwen.json}"
export VIDEO_FEATURE_FOLDER="${VIDEO_FEATURE_FOLDER:-}"
export SAVE_STEPS="${SAVE_STEPS:-25}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

case "$AS_M4_ROLLBACK_MODE" in
  none)
    ;;
  behavior)
    export AS_M4_ENABLE_SCENE_AUDIO=0
    export AS_M4_FORCE_AUDIO_GATE="${AS_M4_FORCE_AUDIO_GATE:-0}"
    ;;
  gate0)
    export AS_M4_FORCE_AUDIO_GATE="${AS_M4_FORCE_AUDIO_GATE:-0}"
    ;;
  weights12k)
    export CKPT_PATH="$AS_M4_BASELINE_CKPT_12K"
    export AS_M4_ENABLE_SCENE_AUDIO=0
    export AS_M4_FORCE_AUDIO_GATE="${AS_M4_FORCE_AUDIO_GATE:-0}"
    ;;
  weights32k)
    export CKPT_PATH="$AS_M4_BASELINE_CKPT_32K"
    export AS_M4_ENABLE_SCENE_AUDIO=0
    export AS_M4_FORCE_AUDIO_GATE="${AS_M4_FORCE_AUDIO_GATE:-0}"
    ;;
  *)
    echo "未知 AS_M4_ROLLBACK_MODE：$AS_M4_ROLLBACK_MODE" >&2
    echo "可用值：none, behavior, gate0, weights12k, weights32k" >&2
    exit 2
    ;;
esac

case "$STAGE" in
  12k-smoke)
    export MAX_STEPS="${MAX_STEPS:-2}"
    export MID_RUN_NAME="${MID_RUN_NAME:-AS-M4-12k-smoke}"
    ;;
  12k-canary20)
    export MAX_STEPS="${MAX_STEPS:-20}"
    export MID_RUN_NAME="${MID_RUN_NAME:-AS-M4-12k-canary20}"
    ;;
  12k-canary150)
    export MAX_STEPS="${MAX_STEPS:-150}"
    export MID_RUN_NAME="${MID_RUN_NAME:-AS-M4-12k-canary150}"
    ;;
  12k-full)
    unset MAX_STEPS
    export MID_RUN_NAME="${MID_RUN_NAME:-AS-M4-12k-full}"
    ;;
  32k-canary20)
    export MODEL_MAX_LENGTH=32000
    export MAX_STEPS="${MAX_STEPS:-20}"
    export MID_RUN_NAME="${MID_RUN_NAME:-AS-M4-32k-canary20}"
    ;;
  32k-canary150)
    export MODEL_MAX_LENGTH=32000
    export MAX_STEPS="${MAX_STEPS:-150}"
    export MID_RUN_NAME="${MID_RUN_NAME:-AS-M4-32k-canary150}"
    ;;
  32k-full)
    export MODEL_MAX_LENGTH=32000
    unset MAX_STEPS
    export MID_RUN_NAME="${MID_RUN_NAME:-AS-M4-32k-full}"
    ;;
  *)
    echo "未知阶段：$STAGE" >&2
    echo "可用阶段：12k-smoke, 12k-canary20, 12k-canary150, 12k-full, 32k-canary20, 32k-canary150, 32k-full" >&2
    exit 2
    ;;
esac

STAMP="$(date +%Y%m%d_%H%M%S)"
CONFIG_FILE="$LOG_DIR/${MID_RUN_NAME}_${STAMP}.env"
LOG_FILE="$LOG_DIR/${MID_RUN_NAME}_${STAMP}.log"
if [[ -e "$CONFIG_FILE" || -e "$LOG_FILE" ]]; then
  SUFFIX=2
  while [[ -e "$LOG_DIR/${MID_RUN_NAME}_${STAMP}-v${SUFFIX}.env" || -e "$LOG_DIR/${MID_RUN_NAME}_${STAMP}-v${SUFFIX}.log" ]]; do
    SUFFIX=$((SUFFIX + 1))
  done
  CONFIG_FILE="$LOG_DIR/${MID_RUN_NAME}_${STAMP}-v${SUFFIX}.env"
  LOG_FILE="$LOG_DIR/${MID_RUN_NAME}_${STAMP}-v${SUFFIX}.log"
fi

{
  echo "STAGE=$STAGE"
  echo "START_TIME=$(date '+%Y-%m-%d %H:%M:%S')"
  echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
  echo "NUM_GPUS=$NUM_GPUS"
  echo "NCCL_SOCKET_IFNAME=$NCCL_SOCKET_IFNAME"
  echo "MODEL_MAX_LENGTH=$MODEL_MAX_LENGTH"
  echo "MAX_STEPS=${MAX_STEPS:-}"
  echo "MID_RUN_NAME=$MID_RUN_NAME"
  echo "CKPT_PATH=$CKPT_PATH"
  echo "DEEPSPEED_CONFIG=$DEEPSPEED_CONFIG"
  echo "TORCHDYNAMO_DISABLE=${TORCHDYNAMO_DISABLE:-}"
  echo "DDP_FIND_UNUSED_PARAMETERS=${DDP_FIND_UNUSED_PARAMETERS:-}"
  echo "M4_CHUNKED_LM_LOSS=$M4_CHUNKED_LM_LOSS"
  echo "M4_CHUNKED_LM_LOSS_TOKENS=$M4_CHUNKED_LM_LOSS_TOKENS"
  echo "M4_CHUNKED_LM_LOSS_CHECKPOINT=$M4_CHUNKED_LM_LOSS_CHECKPOINT"
  echo "M4_FREEZE_LM_HEAD=$M4_FREEZE_LM_HEAD"
  echo "AS_M4_ENABLE_SCENE_AUDIO=$AS_M4_ENABLE_SCENE_AUDIO"
  echo "AS_M4_SCENE_AUDIO_ENCODER_TYPE=$AS_M4_SCENE_AUDIO_ENCODER_TYPE"
  echo "AS_M4_SCENE_AUDIO_BEATS_CHECKPOINT=$AS_M4_SCENE_AUDIO_BEATS_CHECKPOINT"
  echo "AS_M4_SCENE_AUDIO_BEATS_CODE_ROOT=$AS_M4_SCENE_AUDIO_BEATS_CODE_ROOT"
  echo "AS_M4_SCENE_AUDIO_BEATS_CHECKPOINT_SHA256=$AS_M4_SCENE_AUDIO_BEATS_CHECKPOINT_SHA256"
  echo "AS_M4_STREAMING_AV_LR=$AS_M4_STREAMING_AV_LR"
  echo "AS_M4_SCENE_AUDIO_PROJECTOR_LR=$AS_M4_SCENE_AUDIO_PROJECTOR_LR"
  echo "AS_M4_FUSION_INIT=$AS_M4_FUSION_INIT"
  echo "AS_M4_GATE_LOGIT_BIAS=$AS_M4_GATE_LOGIT_BIAS"
  echo "AS_M4_FUSION_MODE=$AS_M4_FUSION_MODE"
  echo "AS_M4_SIMPLE_AUDIO_GATE=$AS_M4_SIMPLE_AUDIO_GATE"
  echo "AS_M4_SCENE_AUDIO_WINDOW_MODE=$AS_M4_SCENE_AUDIO_WINDOW_MODE"
  echo "AS_M4_DYNAMIC_WINDOW_SCALES_SEC=$AS_M4_DYNAMIC_WINDOW_SCALES_SEC"
  echo "AS_M4_DYNAMIC_WINDOW_TOP_K=$AS_M4_DYNAMIC_WINDOW_TOP_K"
  echo "AS_M4_DYNAMIC_WINDOW_NMS_IOU=$AS_M4_DYNAMIC_WINDOW_NMS_IOU"
  echo "AS_M4_DYNAMIC_WINDOW_EMA_BETA=$AS_M4_DYNAMIC_WINDOW_EMA_BETA"
  echo "AS_M4_DYNAMIC_WINDOW_START_SCALE=$AS_M4_DYNAMIC_WINDOW_START_SCALE"
  echo "AS_M4_DYNAMIC_WINDOW_HOLD_SCALE=$AS_M4_DYNAMIC_WINDOW_HOLD_SCALE"
  echo "AS_M4_DYNAMIC_WINDOW_MIN_SCORE=$AS_M4_DYNAMIC_WINDOW_MIN_SCORE"
  echo "AS_M4_DYNAMIC_WINDOW_CAUSAL=$AS_M4_DYNAMIC_WINDOW_CAUSAL"
  echo "AS_M4_FORCE_AUDIO_GATE=$AS_M4_FORCE_AUDIO_GATE"
  echo "AS_M4_ROLLBACK_MODE=$AS_M4_ROLLBACK_MODE"
  echo "AS_M4_BASELINE_CKPT_12K=$AS_M4_BASELINE_CKPT_12K"
  echo "AS_M4_BASELINE_CKPT_32K=$AS_M4_BASELINE_CKPT_32K"
  echo "MM_TUNABLE_PARTS=$MM_TUNABLE_PARTS"
  echo "DATA_PATH=$DATA_PATH"
  echo "VIDEO_FEATURE_FOLDER=$VIDEO_FEATURE_FOLDER"
  echo "SAVE_STEPS=$SAVE_STEPS"
} | tee "$CONFIG_FILE"

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  echo "DRY_RUN=1，仅写入配置：$CONFIG_FILE"
  exit 0
fi

if [[ -e "checkpoints/$MID_RUN_NAME" ]]; then
  echo "拒绝覆盖已有输出目录：checkpoints/$MID_RUN_NAME" >&2
  exit 3
fi

if [[ "${RUN_PREFLIGHT:-1}" == "1" ]]; then
  python scripts/check_m4_repro_preflight.py \
    --allowed_power_limits "${ALLOWED_POWER_LIMITS:-300.00 W,450.00 W}" \
    --audit_json "${PREFLIGHT_AUDIT_JSON:-train_logs/m4_data_audit_generated_audio.json}" \
    --expected_nccl_socket_ifname "$NCCL_SOCKET_IFNAME"
fi

echo "日志文件：$LOG_FILE"
bash scripts/finetune_m4.sh 2>&1 | tee "$LOG_FILE"
